### ISSUE TITLE
May 'cyhal_gpio_xxx()' take a pionter to the GPIO object as a argument but not the object itself

### ISSUE THREAD

**Issue by diverger** [cypresssemiconductorco/wifi-host-driver#3]
Like in WICED, the 'cyhal_gpio_t' maybe a complex type but not only a simple type. So, take a pointer to the GPIO object may be better.

**Comment by rmbk19** [comment]
Hi @diverger, 

cyhal_gpio_t signifies the pin that is referred to. It is not a complex type but an enumeration of all the pins available for a particular device that is specified in the HAL layer. For example, P0_1, and these are already defined for you. So you do not need to initialize a GPIO object or any structure. You can refer to [GPIO HAL Driver documentation](https://cypresssemiconductorco.github.io/psoc6hal/html/group__group__hal__gpio.html) to learn more about the use of cyhal_gpio_t.
For other blocks that require complex structures, like [I2C](https://cypresssemiconductorco.github.io/psoc6hal/html/group__group__hal__i2c.html) - cyhal_i2c_t, the address of the object is passed to the driver APIs.
Please let me know if this helps.

Thanks and Regards, 
Rakshith M B

**Comment by diverger** [comment]
Yes, I checked HAL code, it's more like an 'index' or a 'key' to the real content. May I close my issue?

**Comment by JimTrudeau** [comment]
Absolutely. If you’re satisfied you understand how this works, then we are good! Thanks for raising the issue.

Jim T
