### ISSUE TITLE
CYW4373E

### ISSUE THREAD

**Issue by TomGibsonCS** [cypresssemiconductorco/wifi-host-driver#7]
Hi, does this repository support CYW4373E with SDIO or is only CYW4373 supported? Thanks!

**Comment by Murali-25** [comment]
The CYW4373E should also work with this.

**Comment by cy-chihsien** [comment]
The firmware is only for 4373. 4373E may come up, but the performance won't be optimal.

**Comment by TomGibsonCS** [comment]
Where can we get the firmware for CYW4373E? Is this only available under NDA from Infineon/Cypress?

**Comment by cy-chihsien** [comment]
In the next WHD v2.0.0 (ETA Q4), the FW will become the 4373E version.
