### ISSUE TITLE
RTOS: cy_rtos_terminate_thread never gets called

### ISSUE THREAD

**Issue by imi415** [cypresssemiconductorco/wifi-host-driver#9]
**Prerequisites**

Developing a new RTOS port for WHD

**Description**:

The `cy_rtos_terminate_thread` function which is expected to be called after `cy_rtos_join_thread` never gets called.

**Steps to Reproduce:**

Not applicable

**Expected Result:**

The [documentation](https://infineon.github.io/wifi-host-driver/html/index.html) states this function should be called after `cy_rtos_join_thread`.

**Actual Result:**

This function is not referenced anywhere in the WHD driver code.

**Frequency (1/1, 1/50, 1/100):**

**Build/Commit:**

master branch for now: [9588d90](https://github.com/Infineon/wifi-host-driver/commit/9588d908dcc6fcad1b80733dc98c624e1d649061)

**Target:**

CYW43438

**Host OS and Version:**

Not applicable

**Compiler:**

Not applicable

**Environment**

Not applicable

**Comment by Aditi1091998** [comment]
Hi @imi415 ,

You can go through the https://github.com/Infineon/abstraction-rtos/blob/master/source/COMPONENT_FREERTOS/cyabs_rtos_freertos.c

In the WHD folder, whd_thread.c executes "cy_rtos_join_thread(&thread_info->whd_thread);" which makes the call to the above abstraction-rtos folder.

Thanks

**Comment by imi415** [comment]
Hi @Aditi1091998,
Thanks for your reply.
If I get this correctly, does it means this function is not used by the WHD library and it is the user's decision to call this function in `cy_rtos_join` implementation or just clean-up everything in `cy_rtos_join` and without the need to implement the `cy_rtos_terminate` function?

**Comment by Aditi1091998** [comment]
Hi @imi415 ,
WHD will require the CY RTOS APIs which are implemented in the abstraction-RTOS library. WHD will make call to these APIs like the whd_thread makes a call to the cy_rtos_join function. But the requirement to call the cy_rtos_terminate function is given in the function's declaration. 

/** Terminates another thread.
 *
 * This function is called to terminate another thread and reap the resources claimed
 * by the thread. This should be called both when forcibly terminating another thread
 * as well as any time a thread can exit on its own. For some RTOS implementations
 * this is not required as the thread resources are claimed as soon as it exits. In
 * other cases, this must be called to reclaim resources. Threads that are terminated
 * must still be joined (\ref cy_rtos_join_thread) to ensure their resources are fully
 * cleaned up.

It says that for some RTOS implementations the call to this API is not required as the resources are claimed automatically as the thread exits. But in other cases call to this API is necessary as seen in the cyabs_rtos_freertos.c file. In the cyabs_Rtos_threadx.c file, I don't see the join API making call to the terminate API. So, join API can handle the termination as well. But in case you face any issues, you can make a call to the terminate function to check if that was the missing part.

Thanks
Aditi

**Comment by imi415** [comment]
Hi @Aditi1091998,
Thanks again for your explaination, and I understand this API can be selectively implemented depending on the nature of the underlying RTOS task scheduler. I think this is sufficient to close the issue.

Best Regards
